# Generated by Django 4.0 on 2021-12-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='booking.rooms'),
        ),
    ]
